 /* AUTH */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const JOIN_REQUEST = "REGISTER_REQUEST";
export const JOIN_SUCCESS = "REGISTER_SUCCESS";
export const JOIN_FAILURE = "REGISTER_FAILURE";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAILURE = "GET_STATUS_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
